language: en-US
early_access: false

reviews:
  profile: assertive
  request_changes_workflow: true
  high_level_summary: true
  poem: false
  review_status: true
  
  auto_review:
    enabled: true
    drafts: false
  
  path_filters:
    - "**/*.py"
    - "**/*.ts"
    - "**/*.tsx"
    - "**/*.js"
    - "**/*.jsx"
    - "!**/node_modules/**"
    - "!**/.venv/**"
    - "!**/dist/**"
    - "!**/build/**"
    - "!**/__pycache__/**"
  
  path_instructions:
    - path: "backend/app/**/*.py"
      instructions: |
        Production FastAPI backend for RAG document Q&A system.
        
        Focus on:
        - Security: Check for exposed secrets, SQL injection, file upload vulnerabilities
        - Authentication: Verify JWT validation, endpoint protection
        - Error handling: Ensure proper try/catch and user-friendly errors
        - Performance: Check async/await usage, database queries
        - AI Integration: Verify Cohere/Gemini API error handling and rate limiting
    
    - path: "frontend/src/**/*.{ts,tsx}"
      instructions: |
        React TypeScript frontend.
        
        Focus on:
        - Security: Check for XSS vulnerabilities, token exposure
        - Performance: Look for unnecessary re-renders, memory leaks
        - Error handling: Verify proper error boundaries and user feedback
        - TypeScript: Ensure proper type safety

tone_instructions: "Be thorough and point out security issues, performance problems, and best practices violations. Provide specific code examples."