"""add_embedding_fields_to_documents

Revision ID: a5766d44ed53
Revises: 6332d59653d2
Create Date: 2025-12-01 21:11:26.819874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5766d44ed53'
down_revision: Union[str, Sequence[str], None] = '6332d59653d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('chunks', sa.JSON(), nullable=True, comment='Text chunks for embedding'))
    op.add_column('documents', sa.Column('embeddings', sa.JSON(), nullable=True, comment='Vector embeddings (temporary storage)'))
    op.add_column('documents', sa.Column('chunk_count', sa.Integer(), nullable=True, comment='Number of chunks generated'))
    op.add_column('documents', sa.Column('embedding_model', sa.String(length=100), nullable=True))
    op.add_column('documents', sa.Column('embedding_dimension', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('embedding_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'embedding_date')
    op.drop_column('documents', 'embedding_dimension')
    op.drop_column('documents', 'embedding_model')
    op.drop_column('documents', 'chunk_count')
    op.drop_column('documents', 'embeddings')
    op.drop_column('documents', 'chunks')
    # ### end Alembic commands ###